### ISSUE TITLE
Dynamic create corn job

### ISSUE THREAD

**Issue by zerox12311** [miaowing/nest-schedule#14]
Can I create dynamic corn job?
I want to create with several job with my nest api, and create a corn job with this api.
How to do that?

**Comment by miaowing** [comment]
The 0.5.0 has released, this version has supported dynamic create job.

This is an example:
https://github.com/miaowing/nest-schedule/blob/master/samples/dynamic-schedule.service.ts

**Comment by zerox12311** [comment]
Thank you!!!!
