### ISSUE TITLE
Service's constructor does not run with some specific condition

### ISSUE THREAD

**Issue by nartc** [miaowing/nest-schedule#15]
Hi, 

Thanks for the package. I'm trying to create `ScheduleService` to schedule some task on a daily basis. 

Here's my code
```javascript
@Injectable()
export class ScheduleService extends NestSchedule {
        constructor() {
                super();
        }
 
        @Cron('* * * * *')
        async completeBookings() {
              console.log('testing cron');
        }
}
```
The above snippet runs just fine. But as soon as I start injecting one of my other services: `BookingService`. It seems like the `constructor` never runs. My debugger can hit the breakpoint placed on the `constructor()` but cannot hit the `super()` line.

```javascript
@Module({
    providers: [BookingService],
    exports: [BookingService]
})
export class BookingModule {}

@Module({
     imports: [ScheduleModule.register(...), BookingModule],
     providers: [ScheduleService]
})
export class AppModule {}
```

The above setup is essential what I currently have. 

Note: There are some specific services that I inject into the `ScheduleService` and the cron job runs just fine. There are some services that I inject and it just fails silently (does not run).

Is there anything that you can point me at?

**Comment by nartc** [comment]
Figured out the reason: new Injection Scope that Nest v6 provides

Nest v6 provides a way for you to scope your services to the RequestScope. Which means for every request, a new instance of the Service is created. This also allows you to have access to the Request context in the Service by using `@Inject(REQUEST)`

I utilized this scoped feature and create like a `CurrentUserService` to use across my app. This allows me to not passing in `currentUser` for every single methods that need the current logged in user.

The problem is `CurrentUserService` being request scoped makes whatever services that inject `CurrentUserService` request scoped as well. `CurrentUserService -- injected --> BookingService` Booking Service will be request scoped as well.

A request scoped service cannot be used to run cron job. So  be careful if you're using `Scope.REQUEST`. 

Closing

**Comment by miaowing** [comment]
> Figured out the reason: new Injection Scope that Nest v6 provides
> 
> Nest v6 provides a way for you to scope your services to the RequestScope. Which means for every request, a new instance of the Service is created. This also allows you to have access to the Request context in the Service by using `@Inject(REQUEST)`
> 
> I utilized this scoped feature and create like a `CurrentUserService` to use across my app. This allows me to not passing in `currentUser` for every single methods that need the current logged in user.
> 
> The problem is `CurrentUserService` being request scoped makes whatever services that inject `CurrentUserService` request scoped as well. `CurrentUserService -- injected --> BookingService` Booking Service will be request scoped as well.
> 
> A request scoped service cannot be used to run cron job. So be careful if you're using `Scope.REQUEST`.
> 
> Closing

Thank you very much. 👍
