### ISSUE TITLE
Logger, where is it used ?

### ISSUE THREAD

**Issue by appsolutegeek** [miaowing/nest-schedule#16]
Hi,

I was looking into overriding the logger but I can't see where it is actually used, the examples use console.log, is the logger injected or something ?

I would like to override the logger with my default one but I can't see where nest-schedule is actaully using the logger.

Can you elaborate a little 

Cheers!

**Comment by miaowing** [comment]
The logger will be used to output job execption, such as:

https://github.com/miaowing/nest-schedule/blob/74c2c439ee6a0b94e3aa6a36e15e3d5b672c0031/lib/executor.ts#L26

**Comment by appsolutegeek** [comment]
Ok, thanks.
