### ISSUE TITLE
Recommended to add immediate parameter to Cron and Interval

### ISSUE THREAD

**Issue by StingKo** [miaowing/nest-schedule#20]
eg. 
`@Interval(5000, { immediate: true })`

> immediate: when this parameter is set to true, this scheduled task will be executed immediately after the application is started and ready.

**Comment by miaowing** [comment]
Thanks，I will add this feature in next version

**Comment by kazelone** [comment]
That would execute the job immediately, then every 5000ms.
To execute immediatly and once, you can do
```ts
@Timeout(0)
```
if I understand properly.

**Comment by miaowing** [comment]
You can upgrade to 0.6.0, thanks
