### ISSUE TITLE
Feature Request: No parallel runs for interval

### ISSUE THREAD

**Issue by cloakedch** [miaowing/nest-schedule#21]
It would be great if one could specify whether or not to start multiple runs for an interval.
This would be relevant if the task running in the function takes longer than the interval specified.

Right now one has to do the following:

```
@Interval(1000)
async job() {
  if (this.alreadyRunning) return false;
  this.alreadyRunning = true;

  // do stuff

  this.alreadyRunning = false;
  return false;
}
```

Suggestion: Add a flag in the config such as:
```
@Interval(1000, { singleExecution: true })
```

EDIT: Fixed wrong code.

**Comment by miaowing** [comment]
You can upgrade to 0.6.0 version, use waiting config parameter eg: @Interval(1000, {waiting: true}), thanks.

**Comment by cloakedch** [comment]
That is simply awesome! Thanks for the quick fix!
