### ISSUE TITLE
Creating multiples jobs dynamically

### ISSUE THREAD

**Issue by yassern** [miaowing/nest-schedule#31]
here is my service..
```
import { Injectable } from '@nestjs/common';
import { InjectSchedule, Schedule, IJobConfig } from 'nest-schedule';

@Injectable()
export class ScheduleService {
    constructor(@InjectSchedule() private readonly schedule: Schedule) {}

    createJob(key: string, callback) {
            this.schedule.scheduleTimeoutJob(key, 5000, callback, { waiting: true });
    }

    cancelJob(key: string) {
        this.schedule.cancelJob(key);
    }
}
```
and when i call createJob several times with same parameters, the callback is executed one time and the other calls ends with this error:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
at Function.<anonymous> (/usr/src/app/node_modules/nest-schedule/dist/scheduler.js:99:40)
```

the waiting flag do not help in this case and i think use locks maybe is overcomplicating this case.
the expected behavior for me is that new jobs with same key shouldn't be created like what occurs at this method https://github.com/miaowing/nest-schedule/blob/3d4d7c1561b44622ee4030415a0a19e855025fdb/lib/scheduler.ts#L15

**Comment by miaowing** [comment]
Thank you, I have fixed this issue into 0.6.3
