### ISSUE TITLE
How do I mock crons in test?

### ISSUE THREAD

**Issue by nerdDan** [miaowing/nest-schedule#4]
I am writing e2e testing. I need to disable the cron methods from automatic running, and trigger the methods in testing code manually. I suppose this is a common demand.

Such demand is unfortunately not supported by `nest-schedule`. Would you consider adding such function?

**Comment by miaowing** [comment]
You can use the latest version @0.4.0, and disable the schedule.

```typescript
import { defaults } from 'nest-schedule';

defaults.enable = false;
```
