### ISSUE TITLE
Waiting for scheduled tasks in @Interval(delay) decorator

### ISSUE THREAD

**Issue by biels** [miaowing/nest-schedule#8]
Does the module check if the previous execution of a task is still running when using the Interval decorator? Or even better, does it schedule it after the previous task has finished? 
I tried to look at the code carefully but couldn't figure it out. 

Should I somehow implement a subclass of NestDistributedSchedule with a custom tryLock function?

**Comment by miaowing** [comment]
Sorry, the module does not check the previous execution of a task now, I will try to resolve it in next version.

**Comment by miaowing** [comment]
You can upgrade to 0.6.0 version, using waiting config parameter, eg: @Interval(1000, {waiting: true})
